routes/web.php
<?php

use App\Http\Controllers\CompanyController;
use App\Http\Controllers\EmployeeController;
use App\Http\Controllers\ProfileController;
use Illuminate\Support\Facades\Route;


Route::get('/', function () {
    return redirect()->route('login');
});

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth', 'verified'])->name('dashboard');

Route::middleware('auth')->group(function () {
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');

    Route::resource('companies', CompanyController::class);
    Route::resource('employees', EmployeeController::class);
});

require __DIR__.'/auth.php';

app/Models/Company.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Support\Facades\Storage;

class Company extends Model
{
    use HasFactory;

    protected $fillable = [
        'name',
        'email',
        'logo',
        'website'
    ];

    public function employees(): HasMany
    {
        return $this->hasMany(Employee::class);
    }

    public function remove()
    {
        Storage::delete($this->logo);
        $this->delete();
    }

}

app/Http/Controllers/CompanyController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CompanyRequest;
use App\Models\Company;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Routing\Route;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;
use Illuminate\View\View;

class CompanyController extends Controller
{
    public function index(): View
    {
        $companies = Company::with('employees')->get();

        return view('companies.index', compact('companies'));
    }

    public function create(): View
    {
        return view('companies.create');
    }

    public function store(CompanyRequest $request): RedirectResponse
    {
        if($request->hasFile('logo')) {
            $logo = $request->file('logo')->store('public');
        }

        $company = Company::create([
            'name' => $request->name,
            'email' => $request->email,
            'logo' => $logo ??= null,
            'website' => $request->website,
        ]);
        if (!$company) {
            return redirect()->back()->with('error', 'Not success');
        }

        return redirect()->route('companies.index')->with('success', 'Company created successfully');
    }

    public function edit(Company $company)
    {
        return \view('companies.edit', compact('company'));
    }

    public function update(Request $request, Company $company)
    {
        if($request->hasFile('logo')) {
            if($company->logo) {
                Storage::delete($company->logo);
            }
            $logo = $request->file('logo')->store('public');
        }
        $company->update([
            'name' => $request->name,
            'email' => $request->email,
            'logo' => $logo ??= null,
            'website' => $request->website,
        ]);
        if (!$company) {
            return redirect()->back()->with('error', 'Not success');
        }

        return redirect()->route('companies.index')->with('success', 'Company updated successfully');
    }

    public function destroy(Company $company)
    {
        $company->remove();

        return redirect()->route('companies.index')->with('success', 'Company deleted successfully');
    }
}

resources/views/companies/create.blade.php
@extends('layouts.app')

@section('title', 'Create New Company')
@section('content-header', 'Create New Company')

@section('content-action')
    <a href="{{ route('companies.index') }}" class="btn btn-dark">Go back</a>
@endsection

@section('content')
    <div class="card">
        <div class="card-body">
            <div class="table-responsive-lg">
                <form action="{{ route('companies.store') }}" class="row g-3 needs-validation" method="POST" enctype="multipart/form-data">
                    @csrf
                    <div class="col-md-4">
                        <label for="name" class="form-label">Company title</label>
                        <input type="text" class="form-control" id="name" name="name" placeholder="Input company title" value="{{ old('name') }}">
                        @error('name') <span class="text-danger error">{{ $message }}</span>@enderror
                    </div>
                    <div class="col-md-4">
                        <label for="email" class="form-label">Email</label>
                        <input type="email" class="form-control" id="email" name="email" placeholder="Input email" value="{{ old('email') }}">
                        @error('email') <span class="text-danger error">{{ $message }}</span>@enderror
                    </div>
                    <div class="col-md-4">
                        <label for="website" class="form-label">Website</label>
                        <input type="website" class="form-control" id="website" name="website" placeholder="Input website" value="{{ old('website') }}">
                        @error('website') <span class="text-danger error">{{ $message }}</span>@enderror
                    </div>
                    <div class="col-md-4">
                        <label for="logo">Upload Logo</label>
                        <input type="file" class="form-control" name="logo" id="logo">
                    </div>
                    <div class="text-right col-12">
                        <button class="btn btn-dark">
                            <i class="fa fa-plus"></i> Submit
                        </button>
                        <a href="{{ route('companies.index') }}" class="btn btn-danger">
                            <i class="fa fa-close"></i> Close
                        </a>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/companies/edit.blade.php
@extends('layouts.app')

@section('title', 'Create New Company')
@section('content-header', 'Create New Company')

@section('content-action')
    <a href="{{ route('companies.index') }}" class="btn btn-dark">Go back</a>
@endsection

@section('content')
    <div class="card">
        <div class="card-body">
            <div class="table-responsive-lg">
                <form action="{{ route('companies.update', $company) }}" class="row g-3 needs-validation" method="POST" enctype="multipart/form-data">
                    @csrf
                    @method('PUT')
                    <div class="col-md-4">
                        <label for="name" class="form-label">Company title</label>
                        <input type="text" class="form-control" id="name" name="name" placeholder="Input company title" value="{{ old('name', $company) }}">
                        @error('name') <span class="text-danger error">{{ $message }}</span>@enderror
                    </div>
                    <div class="col-md-4">
                        <label for="email" class="form-label">Email</label>
                        <input type="email" class="form-control" id="email" name="email" placeholder="Input email" value="{{ old('email', $company) }}">
                        @error('email') <span class="text-danger error">{{ $message }}</span>@enderror
                    </div>
                    <div class="col-md-4">
                        <label for="website" class="form-label">Website</label>
                        <input type="website" class="form-control" id="website" name="website" placeholder="Input website" value="{{ old('website', $company) }}">
                        @error('website') <span class="text-danger error">{{ $message }}</span>@enderror
                    </div>
                    @if($company->logo)
                        <img src="{{ Storage::url($company->logo) }}" style="width: 100px; height: 100px;" alt="Company logo">
                    @endif
                    <div class="col-md-4">
                        <label for="logo">Upload Logo</label>
                        <input type="file" class="form-control" name="logo" id="logo">
                    </div>
                    <div class="text-right col-12">
                        <button class="btn btn-dark">
                            <i class="fa-solid fa-pen-to-square"></i> Update
                        </button>
                        <a href="{{ route('companies.index') }}" class="btn btn-danger">
                            <i class="fa fa-close"></i> Close
                        </a>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/companies/index.blade.php
@extends('layouts.app')

@section('title', 'Company List')
@section('content-header', 'Company list')

@section('content-action')
    <a href="{{ route('companies.create') }}" class="btn btn-dark">Add New Company</a>
@endsection

@section('content')

    <div class="card">
        <div class="card-body">
            <div class="table-responsive-lg">
                <table id="company-table" class="table table-bordered table-hover">
                    <thead>
                    <tr>
                        <th>ID</th>
                        <th>Name</th>
                        <th>Email</th>
                        <th>Logo</th>
                        <th>Website</th>
                        <th>Action</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($companies as $company)
                    <tr>
                        <td>{{ $company->id }}</td>
                        <td>{{ $company->name }}</td>
                        <td>{{ $company->email }}</td>
                        <td><img src="{{ Storage::url($company->logo) }}" style="width: 100px; height: 100px;" alt="Company logo"></td>
                        <td>{{ $company->website }}</td>
                        <td>
                            <a href="{{ route('companies.edit', $company) }}" class="btn btn-dark">Edit</a>
                            <a href="#" class="btn btn-danger" onclick="document.getElementById('delete-form').submit()">
                                Delete
                                <form action="{{ route('companies.destroy', $company) }}" method="POST" id="delete-form">
                                    @csrf
                                    @method('DELETE')
                                </form>
                            </a>
                        </td>
                    </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>


@endsection

@push('scripts')
    <script>
        $(function () {
            $('#company-table').DataTable({
                "paging": true,
                "lengthChange": true,
                "searching": true,
                "ordering": true,
                "info": true,
                "autoWidth": false,
                "responsive": true,
            });
        });
    </script>
@endpush