routes/web.php
<?php

use App\Http\Controllers\CompanyController;
use App\Http\Controllers\EmployeeController;
use App\Http\Controllers\ProfileController;
use Illuminate\Support\Facades\Route;


Route::get('/', function () {
    return redirect()->route('login');
});

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth', 'verified'])->name('dashboard');

Route::middleware('auth')->group(function () {
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');

    Route::resource('companies', CompanyController::class);
    Route::resource('employees', EmployeeController::class);
});

require __DIR__.'/auth.php';

app/Models/Employee.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class Employee extends Model
{
    use HasFactory;

    protected $fillable = [
        'first_name',
        'last_name',
        'company_id',
        'email',
        'phone',
    ];

    public function company(): BelongsTo
    {
        return $this->belongsTo(Company::class);
    }
}

app/Http/Controllers/EmployeeController.php
<?php

namespace App\Http\Controllers;

use App\DataTables\EmployeesDataTable;
use App\Http\Requests\EmployeeRequest;
use App\Models\Company;
use App\Models\Employee;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\View\View;

class EmployeeController extends Controller
{
    public function index():View
    {
        $employees = Employee::with('company')->get();

        return view('employees.index', compact('employees'));
    }

    public function create()
    {
        return view('employees.create');
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(EmployeeRequest $request)
    {
        $employee = Employee::create([
            'first_name' => $request->first_name,
            'last_name' => $request->last_name,
            'company_id' => $request->company_id,
            'email' => $request->email,
            'phone' => $request->phone,
        ]);
        if (!$employee) {
            return redirect()->back()->with('error', 'Not success');
        }

        return redirect()->route('employees.index')->with('success', 'Employee created successfully');
    }

    public function edit(Employee $employee)
    {
       return view('employees.edit', compact('employee'));
    }

    public function update(Request $request, Employee $employee)
    {
        $employee->update([
            'first_name' => $request->first_name,
            'last_name' => $request->last_name,
            'company_id' => $request->company_id,
            'email' => $request->email,
            'phone' => $request->phone,
        ]);
        if (!$employee) {
            return redirect()->back()->with('error', 'Not success');
        }

        return redirect()->route('employees.index')->with('success', 'Employee updated successfully');
    }

    public function destroy(Employee $employee)
    {
        $employee->delete();

        return redirect()->route('employees.index')->with('success', 'Employee deleted successfully');
    }
}

resources/views/employees/create.blade.php
@extends('layouts.app')

@section('title', 'Create New Employee')
@section('content-header', 'Create New Employee')

@section('content-action')
    <a href="{{ route('employees.index') }}" class="btn btn-info">Go back</a>
@endsection

@section('content')
    <div class="card">
        <div class="card-body">
            <div class="table-responsive-lg">
                <form action="{{ route('employees.store') }}" class="row g-3 needs-validation" method="POST">
                    @csrf
                    <div class="col-md-4">
                        <label for="first_name" class="form-label">First name</label>
                        <input type="text" class="form-control" id="first_name" name="first_name" placeholder="Enter first name" value="{{ old('first_name') }}">
                        @error('first_name') <span class="text-danger error">{{ $message }}</span>@enderror
                    </div>
                    <div class="col-md-4">
                        <label for="last_name" class="form-label">Last name</label>
                        <input type="text" class="form-control" id="last_name" name="last_name" placeholder="Enter last name" value="{{ old('last_name') }}">
                        @error('last_name') <span class="text-danger error">{{ $message }}</span>@enderror
                    </div>
                    <div class="col-md-4">
                        <label for="company" class="form-label">Company</label>
                        <select class="form-control" name="company_id" id="company">
                            <option value="">Select company</option>
                            @foreach($companies as $company)
                                <option value="{{ $company->id }}">{{ $company->name }}</option>
                            @endforeach
                        </select>
                        @error('company_id') <span class="text-danger error">{{ $message }}</span>@enderror
                    </div>
                    <div class="col-md-4">
                        <label for="email" class="form-label">Email</label>
                        <input type="email" class="form-control" id="email" name="email" placeholder="Enter email" value="{{ old('email') }}">
                        @error('email') <span class="text-danger error">{{ $message }}</span>@enderror
                    </div>
                    <div class="col-md-4">
                        <label for="phone" class="form-label">Phone</label>
                        <input type="text" class="form-control" id="phone" name="phone" placeholder="Enter phone" value="{{ old('phone') }}">
                        @error('email') <span class="text-danger error">{{ $message }}</span>@enderror
                    </div>
                    <div class="text-right col-12">
                        <button class="btn btn-primary">
                            <i class="fa fa-plus"></i> Submit
                        </button>
                        <a href="{{ route('employees.index') }}" class="btn btn-danger">
                            <i class="fa fa-close"></i> Close
                        </a>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/employees/edit.blade.php
@extends('layouts.app')

@section('title', 'Create New Employee')
@section('content-header', 'Create New Employee')

@section('content-action')
    <a href="{{ route('employees.index') }}" class="btn btn-dark">Go back</a>
@endsection

@section('content')
    <div class="card">
        <div class="card-body">
            <div class="table-responsive-lg">
                <form action="{{ route('employees.update', $employee) }}" class="row g-3 needs-validation" method="POST">
                    @csrf
                    @method('PUT')
                    <div class="col-md-4">
                        <label for="first_name" class="form-label">First name</label>
                        <input type="text" class="form-control" id="first_name" name="first_name" placeholder="Enter first name" value="{{ old('first_name', $employee) }}">
                        @error('first_name') <span class="text-danger error">{{ $message }}</span>@enderror
                    </div>
                    <div class="col-md-4">
                        <label for="last_name" class="form-label">Last name</label>
                        <input type="text" class="form-control" id="last_name" name="last_name" placeholder="Enter last name" value="{{ old('last_name', $employee) }}">
                        @error('last_name') <span class="text-danger error">{{ $message }}</span>@enderror
                    </div>
                    <div class="col-md-4">
                        <label for="company" class="form-label">Company</label>
                        <select class="form-control" name="company_id" id="company">
                            <option value="">Select company</option>
                            @foreach($companies as $company)
                                <option value="{{ $company->id }}" @if($employee->company->id == $company->id) selected @endif >{{ $company->name }}</option>
                            @endforeach
                        </select>
                        @error('company_id') <span class="text-danger error">{{ $message }}</span>@enderror
                    </div>
                    <div class="col-md-4">
                        <label for="email" class="form-label">Email</label>
                        <input type="email" class="form-control" id="email" name="email" placeholder="Enter email" value="{{ old('email', $employee) }}">
                        @error('email') <span class="text-danger error">{{ $message }}</span>@enderror
                    </div>
                    <div class="col-md-4">
                        <label for="phone" class="form-label">Phone</label>
                        <input type="text" class="form-control" id="phone" name="phone" placeholder="Enter phone" value="{{ old('phone', $employee) }}">
                        @error('email') <span class="text-danger error">{{ $message }}</span>@enderror
                    </div>
                    <div class="text-right col-12">
                        <button class="btn btn-dark">
                            <i class="fa-solid fa-pen-to-square"></i> Update
                        </button>
                        <a href="{{ route('employees.index') }}" class="btn btn-danger">
                            <i class="fa fa-close"></i> Close
                        </a>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/employees/index.blade.php
@extends('layouts.app')

@section('title', 'Employee List')
@section('content-header', 'Employee list')

@section('content-action')
    <a href="{{ route('employees.create') }}" class="btn btn-dark">Add New Employee</a>
@endsection

@section('content')
    <p class="login-box-msg">@include('messages.flash-message')</p>
    <div class="card">
        <div class="card-body">
            <div class="table-responsive-lg">
                <table id="employee-table" class="table table-bordered table-hover">
                    <thead>
                    <tr>
                        <th>ID</th>
                        <th>First Name</th>
                        <th>Last Name</th>
                        <th>Company</th>
                        <th>Email</th>
                        <th>Phone</th>
                        <th>Action</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($employees as $employee)
                        <tr>
                            <td>{{ $employee->id }}</td>
                            <td>{{ $employee->first_name }}</td>
                            <td>{{ $employee->last_name }}</td>
                            <td>{{ $employee->company->name }}</td>
                            <td>{{ $employee->email }}</td>
                            <td>{{ $employee->phone }}</td>
                            <td>
                                <a href="{{ route('employees.edit', $employee) }}" class="btn btn-dark">Edit</a>
                                <a href="#" class="btn btn-danger" onclick="document.getElementById('delete-form').submit()">
                                        Delete
                                    <form action="{{ route('employees.destroy', $employee) }}" method="POST" id="delete-form">
                                        @csrf
                                        @method('DELETE')
                                    </form>
                                </a>
{{--                                <a href="{{ route('employees.destroy', $employee) }}" class="btn btn-danger">Delete</a>--}}
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection

@push('scripts')
    <script>
        $(function () {
            $('#employee-table').DataTable({
                "paging": true,
                "lengthChange": true,
                "searching": true,
                "ordering": true,
                "info": true,
                "autoWidth": false,
                "responsive": true,
            });
        });
    </script>
@endpush